package:
  name: timbr-machine
  version: 0.1

build:
  number: 0

requirements:
  build:
    - setuptools
    - dask
    - ipython
    - h5py
    - pymongo >=2.8

  run:
    - dask
    - ipython
    - pymongo >=2.8

about:
  home: https://bitbucket.org/timbr-io/timbr-machine
  license: Private
